# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6156e1d6cf64cf816d9ac9f85f318cf0bbac1d796cd23f30f7ed5bd9cadc40a68119b56e7c808baecb765b702e383195a2c51ef6d8e91a7c245e9e2956417c

test:
  secret_key_base: cb9d1c2eca3d7b437e8c7a50e058be7923484b3d5af121b083aed55c6c9035a0d0a7325f8e72737f54a31295d3ec2701ce6ed965613255f44c09af621c6d6fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
